CRITICAL - 2023-03-29 00:52:16 --> Undefined variable: p
#0 C:\xampp\htdocs\kinerja2022\app\Views\tabel\indexEditKinerja.php(77): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 77, Array)
#1 C:\xampp\htdocs\kinerja2022\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\kinerja2022\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\kinerja2022\system\Common.php(1097): CodeIgniter\View\View->render('tabel/indexEdit...', Array, true)
#4 C:\xampp\htdocs\kinerja2022\app\Controllers\EditKinerja.php(26): view('tabel/indexEdit...', Array)
#5 C:\xampp\htdocs\kinerja2022\system\CodeIgniter.php(824): App\Controllers\EditKinerja->EditKinerjaSKPD('2')
#6 C:\xampp\htdocs\kinerja2022\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EditKinerja))
#7 C:\xampp\htdocs\kinerja2022\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\kinerja2022\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\kinerja2022\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2023-03-29 09:50:45 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2023-03-29 09:50:45 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\kinerja2022\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\kinerja2022\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\kinerja2022\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\kinerja2022\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\kinerja2022\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\kinerja2022\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 C:\xampp\htdocs\kinerja2022\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 C:\xampp\htdocs\kinerja2022\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 C:\xampp\htdocs\kinerja2022\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\xampp\htdocs\kinerja2022\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\kinerja2022\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\kinerja2022\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-03-29 09:50:45 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\kinerja2022\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\kinerja2022\app\Views\errors\html\error_exception.php(96): print_r(Object(Myth\Auth\Controllers\AuthController), true)
#2 C:\xampp\htdocs\kinerja2022\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\kinerja2022\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\kinerja2022\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
